/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.33
 * Generated at: 2024-12-05 15:18:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import jakarta.servlet.http.*;
import java.sql.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Library Management System</title>\n");
      out.write("    <!-- Bootstrap CSS -->\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("    <!-- Font Awesome -->\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\">\n");
      out.write("    <style>\n");
      out.write("        :root {\n");
      out.write("            --primary-color: #1a1a2e;\n");
      out.write("            --secondary-color: #16213e;\n");
      out.write("            --accent-color: #0f3460;\n");
      out.write("            --text-color: #e94560;\n");
      out.write("            --light-text: #f8f9fa;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        body {\n");
      out.write("            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n");
      out.write("            background-color: var(--primary-color);\n");
      out.write("            color: var(--light-text);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .navbar {\n");
      out.write("            background-color: var(--secondary-color);\n");
      out.write("            padding: 1rem 2rem;\n");
      out.write("            box-shadow: 0 2px 4px rgba(0,0,0,0.2);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .navbar-brand {\n");
      out.write("            color: var(--text-color) !important;\n");
      out.write("            font-weight: bold;\n");
      out.write("            font-size: 1.5rem;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .nav-link {\n");
      out.write("            color: var(--light-text) !important;\n");
      out.write("            margin: 0 10px;\n");
      out.write("            transition: all 0.3s ease;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .nav-link:hover {\n");
      out.write("            color: var(--text-color) !important;\n");
      out.write("            transform: translateY(-2px);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .hero-section {\n");
      out.write("            background: linear-gradient(135deg, var(--secondary-color), var(--accent-color));\n");
      out.write("            color: var(--light-text);\n");
      out.write("            padding: 3rem 0;\n");
      out.write("            margin-bottom: 2rem;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .hero-section .welcome-name {\n");
      out.write("            color: var(--text-color);\n");
      out.write("            font-weight: bold;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .feature-card {\n");
      out.write("            background: var(--secondary-color);\n");
      out.write("            border-radius: 15px;\n");
      out.write("            padding: 2.5rem 2rem;\n");
      out.write("            margin: 1rem;\n");
      out.write("            height: 400px;\n");
      out.write("            width: 100%;\n");
      out.write("            display: flex;\n");
      out.write("            flex-direction: column;\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: flex-start;\n");
      out.write("            transition: transform 0.3s ease, box-shadow 0.3s ease;\n");
      out.write("            box-shadow: 0 4px 15px rgba(0,0,0,0.2);\n");
      out.write("            color: var(--light-text);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .feature-card:hover {\n");
      out.write("            transform: translateY(-10px);\n");
      out.write("            box-shadow: 0 8px 25px rgba(0,0,0,0.3);\n");
      out.write("            background: var(--accent-color);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .feature-icon {\n");
      out.write("            font-size: 4rem;\n");
      out.write("            color: var(--text-color);\n");
      out.write("            margin-bottom: 2rem;\n");
      out.write("            height: 80px;\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: center;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .feature-card h3 {\n");
      out.write("            font-size: 1.75rem;\n");
      out.write("            margin-bottom: 1.5rem;\n");
      out.write("            color: var(--light-text);\n");
      out.write("            font-weight: 600;\n");
      out.write("            height: 40px;\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: center;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .feature-card p {\n");
      out.write("            color: #b0b0b0;\n");
      out.write("            margin-bottom: 2rem;\n");
      out.write("            flex-grow: 1;\n");
      out.write("            font-size: 1.1rem;\n");
      out.write("            line-height: 1.6;\n");
      out.write("            text-align: center;\n");
      out.write("            height: 80px;\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: center;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .btn-custom {\n");
      out.write("            background-color: var(--text-color);\n");
      out.write("            color: var(--light-text);\n");
      out.write("            padding: 0.8rem 2rem;\n");
      out.write("            border-radius: 30px;\n");
      out.write("            border: none;\n");
      out.write("            font-weight: 600;\n");
      out.write("            letter-spacing: 0.5px;\n");
      out.write("            transition: all 0.3s ease;\n");
      out.write("            text-decoration: none;\n");
      out.write("            margin-top: auto;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .btn-custom:hover {\n");
      out.write("            background: var(--light-text);\n");
      out.write("            color: var(--text-color);\n");
      out.write("            transform: scale(1.05);\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <!-- Navigation Bar -->\n");
      out.write("    <nav class=\"navbar navbar-expand-lg navbar-dark\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <a class=\"navbar-brand\" href=\"home.jsp\">\n");
      out.write("                <i class=\"fas fa-book-reader me-2\"></i>CITY LIBRARY\n");
      out.write("            </a>\n");
      out.write("            <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarNav\">\n");
      out.write("                <span class=\"navbar-toggler-icon\"></span>\n");
      out.write("            </button>\n");
      out.write("            <div class=\"collapse navbar-collapse\" id=\"navbarNav\">\n");
      out.write("                <ul class=\"navbar-nav ms-auto\">\n");
      out.write("                    <li class=\"nav-item\">\n");
      out.write("                        <a class=\"nav-link active\" href=\"home.jsp\">Home</a>\n");
      out.write("                    </li>\n");
      out.write("                    <li class=\"nav-item\">\n");
      out.write("                        <a class=\"nav-link\" href=\"viewbooks.jsp\">View Books</a>\n");
      out.write("                    </li>\n");
      out.write("                    <li class=\"nav-item\">\n");
      out.write("                        <a class=\"nav-link\" href=\"search.jsp\">Search Books</a>\n");
      out.write("                    </li>\n");
      out.write("                    <li class=\"nav-item\">\n");
      out.write("                        <a class=\"nav-link\" href=\"purchase-books.jsp\">\n");
      out.write("                            <i class=\"fas fa-shopping-cart me-1\"></i>Purchase Books\n");
      out.write("                        </a>\n");
      out.write("                    </li>\n");
      out.write("                    ");

                    String userType = (String) session.getAttribute("userType");
                    if (userType != null && userType.equals("admin")) {
                    
      out.write("\n");
      out.write("                        <li class=\"nav-item\">\n");
      out.write("                            <a class=\"nav-link\" href=\"admin-dashboard.jsp\">\n");
      out.write("                                <i class=\"fas fa-cog\"></i> Admin Dashboard\n");
      out.write("                            </a>\n");
      out.write("                        </li>\n");
      out.write("                    ");
 } 
      out.write("\n");
      out.write("                    <li class=\"nav-item\">\n");
      out.write("                        <a class=\"nav-link\" href=\"index.jsp\">\n");
      out.write("                            <i class=\"fas fa-sign-out-alt me-1\"></i>Logout\n");
      out.write("                        </a>\n");
      out.write("                    </li>\n");
      out.write("                </ul>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </nav>\n");
      out.write("\n");
      out.write("    <!-- Hero Section -->\n");
      out.write("    <section class=\"hero-section text-center\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <h1 class=\"display-4 mb-3\">Welcome, <span class=\"welcome-name\">");
      out.print( session.getAttribute("username") );
      out.write("</span>!</h1>\n");
      out.write("            <p class=\"lead mb-0\">Manage your library efficiently with our comprehensive management system.</p>\n");
      out.write("        </div>\n");
      out.write("    </section>\n");
      out.write("\n");
      out.write("    <!-- Features Section -->\n");
      out.write("    <section class=\"container\" style=\"margin-top: -30px;\">\n");
      out.write("        <div class=\"row g-4\">\n");
      out.write("            <div class=\"col-md-4\">\n");
      out.write("                <div class=\"feature-card text-center\">\n");
      out.write("                    <i class=\"fas fa-book feature-icon\"></i>\n");
      out.write("                    <h3>Browse Books</h3>\n");
      out.write("                    <p>Explore our extensive collection of books available in the library.</p>\n");
      out.write("                    <a href=\"viewbooks.jsp\" class=\"btn btn-custom\">View Books</a>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-md-4\">\n");
      out.write("                <div class=\"feature-card text-center\">\n");
      out.write("                    <i class=\"fas fa-search feature-icon\"></i>\n");
      out.write("                    <h3>Quick Search</h3>\n");
      out.write("                    <p>Find any book instantly using our powerful search feature.</p>\n");
      out.write("                    <a href=\"search.jsp\" class=\"btn btn-custom\">Search Now</a>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-md-4\">\n");
      out.write("                <div class=\"feature-card text-center\">\n");
      out.write("                    <i class=\"fas fa-shopping-cart feature-icon\"></i>\n");
      out.write("                    <h3>Purchase Books</h3>\n");
      out.write("                    <p>Buy your favorite books from our collection.</p>\n");
      out.write("                    <a href=\"purchase-books.jsp\" class=\"btn btn-custom\">Purchase Now</a>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </section>\n");
      out.write("\n");
      out.write("    <!-- Bootstrap JS and Popper.js -->\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js\"></script>\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
